/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';
import { IProductFeatureViewProps } from './product-feature';
import { imageAlignment } from './product-feature.props.autogenerated';

const _renderImage = (productImageUrl: string, productname: string): JSX.Element => {
    return <img src={productImageUrl} alt={productname} className='img-fluid p-3' />;
};

const _renderInfo = (
    productName: string,
    productInfo: string,
    productPrice: string,
    buttonInfo: string,
    productTitledId: string
): JSX.Element => {
    return (
        <div className='container'>
            <h2 id={productTitledId}>{productName}</h2>
            <p>{productInfo}</p>
            <p>{productPrice}</p>
            <button type='button' className='btn btn-primary'>
                {buttonInfo}
            </button>
        </div>
    );
};

export default (props: IProductFeatureViewProps) => {
    const { productName, productInfo, productImageUrl, productPrice, buttonInfo, alignment } = props;

    let left;
    let right;
    if (alignment === imageAlignment.left) {
        left = _renderImage(productImageUrl, productName);
        right = _renderInfo(productName, productInfo, productPrice, buttonInfo, 'product_Title_1');
    } else {
        left = _renderInfo(productName, productInfo, productPrice, buttonInfo, 'product_Title_2');
        right = _renderImage(productImageUrl, productName);
    }

    return (
        <div className='row align-items-center'>
            <div className='col-md-6'>{left}</div>
            <div className='col-md-6'>{right}</div>
        </div>
    );
};
