import * as React from 'react';
import { SimpleProductWithPrice } from '../../actions/get-product-with-variant-price.action';
import { IProductFeatureViewProps } from './product-feature';
import { imageAlignment } from './product-feature.props.autogenerated';

const _renderImage = (productImageUrl: string | undefined, productName: string) => {
    return <img src={productImageUrl} alt={productName} className='img-fluid p-3' />;
};

const _renderInfo = (
    productName: string,
    productInfo: string,
    productPrice: string,
    buttonInfo: string,
    product: SimpleProductWithPrice | undefined
): JSX.Element => {
    return (
        <div className='container'>
            <h2 className=''>{productName}</h2>
            <p>{productInfo}</p>
            <div className='product_base'>
                {
                    <h3>
                        <span>Chained Product Base Price:</span>
                    </h3>
                }
                <b>
                    <span className='chain_basePrice product-feature-title'>{product?.variantPrice?.BasePrice}</span>
                </b>
            </div>
            <div className='product_variant'>
                {
                    <h3>
                        <span>Chained Variant Adjusted Price With Currency:</span>
                    </h3>
                }
                <b>
                    <span className='chain_variantPrice product-feature-title'>
                        {product?.variantPrice?.AdjustedPrice} {product?.variantPrice?.CurrencyCode}
                    </span>
                </b>
            </div>
        </div>
    );
};

export default (props: IProductFeatureViewProps) => {
    const { productName, productInfo, productImageUrl, productPrice, buttonInfo, alignment, productVariantDetail } = props;
    let left;
    let right;
    if (alignment === imageAlignment.left) {
        left = _renderImage(productImageUrl, productName);
        right = _renderInfo(productName, productInfo, productPrice, buttonInfo, productVariantDetail);
    } else {
        left = _renderInfo(productName, productInfo, productPrice, buttonInfo, productVariantDetail);
        right = _renderImage(productImageUrl, productName);
    }
    return (
        <div className='row align-items-center'>
            <div className='col-md-6'>{left}</div>
            <div className='col-md-6'>{right}</div>
        </div>
    );
};
